// Server-truth notes next to the vault (vault.js stays Lumen's): which quests THIS server offers,
// by the town/map of their start NPC, for a level band — and what the dead ones are.
//   bun agent/enrich.js [--min 1 --max 30]   → knowledge/Server/Quests offered (lv 1-30).md
// Overwritten on every run (generated, like World/). Uses quests.js verdicts and the vault's NPC
// "Found in" links, so World/ must exist (run vault.js first).
import { mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";
import { questBook } from "./quests.js";

const { values: o } = parseArgs({
  options: { game: { type: "string", default: "http://127.0.0.1:3102" }, min: { type: "string", default: "1" }, max: { type: "string", default: "30" } },
  strict: true,
});
const KNOW = join(import.meta.dir, "knowledge");
const book = await questBook(o.game);
const safe = (s) => String(s).replace(/[\\/:*?"<>|#^[\]]/g, "").replace(/\s+/g, " ").trim(); // same as vault.js
const qNote = (q) => `[[${safe(q.name)} (Quest ${q.id})]]`;
const npcLink = (id) => `[[${safe(book.npcName(id))} (NPC ${id})]]`;

const npcHome = new Map();
const NPC_DIR = join(KNOW, "World", "NPCs");
for (const f of readdirSync(NPC_DIR)) {
  const id = f.match(/\(NPC (\d+)\)\.md$/)?.[1];
  const home = readFileSync(join(NPC_DIR, f), "utf8").match(/## Found in\n- (\[\[[^\]]+\]\])/)?.[1];
  if (id && home) npcHome.set(Number(id), home);
}

const [min, max] = [Number(o.min), Number(o.max)];
const byMap = new Map();
const dead = { UNSUPPORTED: 0, GATED: 0, UNREACHABLE: 0 };
for (const q of Object.values(book.records)) {
  const s = q.stages[0].check;
  const lo = s.lvmin ?? 1, hi = s.lvmax ?? 200;
  if (hi < min || lo > max || !s.npc) continue;
  const v = book.verdict(q).split(" ")[0];
  if (v !== "OK") { dead[v] = (dead[v] ?? 0) + 1; continue; }
  const home = npcHome.get(s.npc) ?? "(NPC location unknown)";
  if (!byMap.has(home)) byMap.set(home, []);
  const end = q.stages[1] ?? { act: {} };
  const reward = [end.act.exp ? `${end.act.exp} EXP` : "", end.act.money ? `${end.act.money} mesos` : ""].filter(Boolean).join(", ");
  const need = book.objectives(q).map((x) => `${x.kind} ${x.name} ×${x.count}`).join(", ") || "talk";
  const after = s.quests.filter((p) => p.state >= 1).map((p) => `${p.id}`).join(", ");
  byMap.get(home).push(`| ${qNote(q)} | ${lo}–${s.lvmax ?? "any"} | ${npcLink(s.npc)} | ${need} | ${reward || "items"} | ${after} |`);
}

const lines = [
  `# Quests this server offers (level ${min}–${max})`, "",
  `Generated by \`agent/enrich.js\` from the server-supported quest data (see [[Quest availability on this server]]).`,
  `Excluded as dead in this band: ${Object.entries(dead).map(([k, n]) => `${n} ${k}`).join(", ")}. "after" = prerequisite quest ids.`,
  `Check one map live with \`bun agent/quests.js --map <id> --level <yours>\`; your progress with \`questlog.js\`.`, "",
];
for (const [home, rows] of [...byMap].sort((a, b) => a[0].localeCompare(b[0]))) {
  lines.push(`## ${home}`, "", "| Quest | Lv | Start | Do | Reward | after |", "|---|---|---|---|---|---|", ...rows, "");
}
mkdirSync(join(KNOW, "Server"), { recursive: true });
const out = join(KNOW, "Server", `Quests offered (lv ${min}-${max}).md`);
writeFileSync(out, lines.join("\n"));
console.log(`[enrich] ${out}: ${[...byMap.values()].reduce((n, r) => n + r.length, 0)} quests in ${byMap.size} places; dead ${JSON.stringify(dead)}`);
