// Where should a character of level L / max HP H train? Reads every map's monsters with their real
// stats (level, maxHP, touch damage PADamage, EXP) from the map manifests the client loads.
//   bun agent/training.js --level 4 --hp 65                 best maps for you, safest first
//   bun agent/training.js --level 4 --hp 65 --map 1010000   per-monster verdicts on one map
//   bun agent/training.js --note                            write knowledge/Server/Training maps by level.md
// Danger model (ponytail: no defence/avoid math): a touch hits for about PADamage × --scale, so
//   hitsToDie = H / (PADamage × scale). Calibration knob --scale (default 0.5): observed Shroom touches
//   (PADamage 17) took 4–8 HP from an unarmoured level 3–4 beginner. "safe" ≥ 5 hits and mob level ≤ L+2; "risky" ≥ 3 hits; else "deadly".
// Value = EXP per HP you must chew through (exp / maxHP), times how many there are.
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { parseArgs } from "node:util";

const { values: o } = parseArgs({
  options: {
    game: { type: "string", default: "http://127.0.0.1:3102" },
    level: { type: "string" }, hp: { type: "string" }, map: { type: "string" },
    note: { type: "boolean", default: false }, top: { type: "string", default: "12" },
    scale: { type: "string", default: "0.5" },
  },
  strict: true,
});
const origin = new URL(o.game).origin;
const SCALE = Number(o.scale);
const c = await (await fetch(`${origin}/generated/catalog.json`)).json();

/** One map's monsters: [{id, name, count, level, maxHP, touch, exp}] (towns and empty maps → []). */
async function mobsOn(key) {
  const m = await (await fetch(new URL(c.maps[key].url, origin))).json().catch(() => null);
  if (!m?.life) return [];
  const counts = new Map();
  for (const p of m.life.placements) {
    const t = m.life.templates[p.template];
    if (t?.kind === "mob" && t.info?.maxHP > 1 && t.info?.exp > 0) counts.set(p.template, (counts.get(p.template) ?? 0) + 1);
  }
  return [...counts].map(([k, n]) => {
    const t = m.life.templates[k];
    return { id: Number(t.originalId), name: t.name, count: n, level: t.info.level, maxHP: t.info.maxHP, touch: t.info.PADamage, exp: t.info.exp };
  });
}

export function verdict(mob, level, hp) {
  const hits = mob.touch ? hp / (mob.touch * SCALE) : Infinity;
  if (hits >= 5 && mob.level <= level + 2) return "safe";
  if (hits >= 3 && mob.level <= level + 5) return "risky";
  return "deadly";
}

async function allMaps() {
  const out = [];
  const keys = Object.keys(c.maps);
  for (let i = 0; i < keys.length; i += 24) {
    const batch = await Promise.all(keys.slice(i, i + 24).map(async (k) => ({ id: Number(k), name: c.mapNames[Number(k)] ?? k, mobs: await mobsOn(k) })));
    out.push(...batch.filter((b) => b.mobs.length));
  }
  return out;
}

function rank(maps, level, hp) {
  return maps
    .map((m) => {
      const v = m.mobs.map((x) => ({ ...x, v: verdict(x, level, hp) }));
      const ok = v.filter((x) => x.v !== "deadly");
      const value = ok.reduce((s, x) => s + (x.exp / x.maxHP) * x.count, 0);
      const deadly = v.filter((x) => x.v === "deadly").reduce((s, x) => s + x.count, 0);
      const risky = v.filter((x) => x.v === "risky").reduce((s, x) => s + x.count, 0);
      return { ...m, v, value, deadly, risky };
    })
    .filter((m) => m.value > 0 && m.deadly === 0 && !/Hidden|Event|Party|PQ|Quest|Zakum|Boss|Dojo|Monster Carnival/i.test(m.name))
    .sort((a, b) => a.risky - b.risky || b.value - a.value);
}
const fmt = (m) => `${m.name} (${m.id}) — ${m.v.map((x) => `${x.name} lv${x.level} ${x.maxHP}HP hit${x.touch} ×${x.count}${x.v === "risky" ? " (risky)" : ""}`).join(", ")}`;

if (o.map) {
  const [level, hp] = [Number(o.level), Number(o.hp)];
  for (const x of await mobsOn(String(o.map).padStart(9, "0")))
    console.log(`${x.name} (${x.id}) lv${x.level} HP ${x.maxHP} touch ${x.touch} exp ${x.exp} ×${x.count} → ${level ? verdict(x, level, hp) : ""}`);
} else if (o.note) {
  const maps = await allMaps();
  // Rough beginner/first-job max HP by level, for the table only (agents should use their own).
  const hpAt = (L) => (L <= 10 ? 45 + 5 * L : 95 + 20 * (L - 10)); // Wayfinder: 65 HP at level 4 (beginner)
  const lines = ["# Training maps by level", "",
    "Generated by `agent/training.js --note` from every map's monster stats (level, max HP, touch damage, EXP).",
    "Assumed max HP ≈ 45 + 5×level up to 10 (observed: 65 at level 4), then +20/level; check yourself with `training.js --level L --hp H`.",
    "\"safe\" = ≥5 touches to die (touch ≈ PADamage × 0.5, calibrated from Shroom hits) and the monster is ≤2 levels above you; ⚠ = risky (≥3 touches). Maps with any deadly monster are left out.", ""];
  for (const L of [1, 3, 5, 7, 10, 13, 16, 20, 25, 30]) {
    lines.push(`## Level ${L} (≈${hpAt(L)} HP)`, "");
    for (const m of rank(maps, L, hpAt(L)).slice(0, 8)) lines.push(`- [[${m.name.replace(/[\\/:*?"<>|#^[\]]/g, "").replace(/\s+/g, " ").trim()} (${m.id})]] — ${m.v.map((x) => `${x.name} lv${x.level}/${x.maxHP} HP ×${x.count}${x.v === "risky" ? " ⚠" : ""}`).join(", ")}`);
    lines.push("");
  }
  mkdirSync(join(import.meta.dir, "knowledge", "Server"), { recursive: true });
  const out = join(import.meta.dir, "knowledge", "Server", "Training maps by level.md");
  writeFileSync(out, lines.join("\n"));
  console.log(`[training] ${out}`);
} else {
  if (!o.level || !o.hp) throw new Error("--level and --hp required (or --map / --note)");
  for (const m of rank(await allMaps(), Number(o.level), Number(o.hp)).slice(0, Number(o.top))) console.log(fmt(m));
}
